### ISSUE TITLE
Docker PromteImage should allow targetTag to be set

### ISSUE THREAD

**Issue by Emilio-Pega** [cdancy/artifactory-rest#3]
The Docker PromteImage logic is missing the ability to set the target tag.  This is required when we want to promote a CI build image like 1.0.0-1234 to a final image 1.0.0 without needing to pull, retag, and push the image.

https://www.jfrog.com/confluence/display/JFROG/Docker+Registry

![Screenshot from 2020-03-05 07-55-21](https://user-images.githubusercontent.com/54679517/75983556-c1667e80-5eb6-11ea-81fe-bca08058cc87.png)

**Comment by cdancy** [comment]
@Emilio-Pega `v0.9.8` has been released with this change. Thanks for the PR!

**Comment by Emilio-Pega** [comment]
Thanks for the quick turnaround @cdancy now onto the rest gradle plugin :)
