### ISSUE TITLE
org.jclouds.io.Payload is missing when declaring artifactory-rest as a dependency

### ISSUE THREAD

**Issue by martinda** [cdancy/artifactory-rest#87]
When a project depends on `artifactory-rest` and tries to use the `ArtifactApi.deployArtifact()`, the user of the library must also declare a dependency on `org.apache.jclouds:jclouds-core` because the API of that method uses `org.jclouds.io.Payload`.

The method signature is:
```java
Artifact deployArtifact(
    @PathParam("repoKey") String repoKey,
    @PathParam("itemPath") String itemPath,
    Payload inputStream,
    @Nullable @BinderParam(BindMatrixPropertiesToPath.class) Map<String, List<String>> properties);
```

The type of the 3rd argument is `org.jclouds.io.Payload`. So to use this method, users must also declare a dependency on `org.apache.jclouds:jcloud-core`.

Instead, I would like to propose to expose the jclouds dependency as an api using [gradle's api configuration](https://docs.gradle.org/current/userguide/java_library_plugin.html#sec:java_library_recognizing_dependencies). I am studying the problem and working on a PR and I hope to send it in soon.

I would like to find a way to test it too, but I just begin to understand these concepts!

CC @Dhivyaa21

**Comment by martinda** [comment]
So what works is to declare `jclouds-core` using the `api` configuration provided by the `java-library` plugin:

```groovy
plugins {
    id 'java-library'
}

// ...
dependencies {
    // ...
    api ("org.apache.jclouds:jclouds-core:${jcloudsVersion")
    // ....
}
```

But I am also trying to create a test to prove that's the only element needed to be in the `api` configuration.

**Comment by Dhivyaa21** [comment]
I agree with @martinda. The problem with `implementation` configuration is that the dependencies are not available during the compile time. However, gradle adds them with a `runtime` scope in the pom.xml. Since this project will be used as a dependency in other projects, it is better to use `api` for `jclouds-core`.
